#pragma once

#include <cstdint>
#include <string_view>

namespace qjsp {

enum class AtomType : uint8_t {
  string = 0,
  symbol = 1,
};

using Atom               = uint32_t;
constexpr Atom kAtomNull = 0;

// ─── Atom enum (from quickjs-atom.h) ───────────────────────────────────────
// Order matters: first 27 are keywords, parser relies on range checks.
enum class AtomEnum : Atom {
  _null = 1,
  _false,
  _true,
  _if,
  _else,
  _return,
  _var,
  _this,
  _delete,
  _void,
  _typeof,
  _new,
  _in,
  _instanceof,
  _do,
  _while,
  _for,
  _break,
  _continue,
  _switch,
  _case,
  _default,
  _throw,
  _try,
  _catch,
  _finally,
  _function,
  _debugger,
  _with,
  _class,
  _const,
  _enum,
  _export,
  _extends,
  _import,
  _super,
  _implements,
  _interface,
  _let,
  _package,
  _private,
  _protected,
  _public,
  _static,
  _yield,
  _await,
  empty_string,
  keys,
  _size_,
  length,
  fileName,
  lineNumber,
  columnNumber,
  message,
  cause,
  errors,
  stack,
  name,
  toString,
  toLocaleString,
  valueOf,
  eval_,
  prototype,
  constructor,
  configurable,
  writable,
  enumerable,
  value_,
  get,
  set,
  of,
  __proto__,
  undefined_,
  number,
  boolean,
  string,
  object,
  symbol,
  integer,
  unknown,
  arguments,
  callee,
  caller,
  _eval_,
  _ret_,
  _var_,
  _arg_var_,
  _with_,
  lastIndex,
  target,
  index,
  input,
  defineProperties,
  apply,
  join,
  concat,
  split,
  construct,
  getPrototypeOf,
  setPrototypeOf,
  isExtensible,
  preventExtensions,
  has,
  deleteProperty,
  defineProperty,
  getOwnPropertyDescriptor,
  ownKeys,
  add,
  done,
  next,
  values,
  source,
  flags,
  global,
  unicode,
  raw,
  rawJSON,
  new_target,
  this_active_func,
  home_object,
  computed_field,
  static_computed_field,
  class_fields_init,
  brand,
  hash_constructor,
  as,
  from,
  meta,
  _default_,
  _star_,
  Module,
  then,
  resolve,
  reject,
  promise,
  proxy,
  revoke,
  async,
  exec,
  groups,
  indices,
  _status_,
  reason,
  globalThis,
  bigint,
  minus_zero,
  Infinity_,
  minus_Infinity,
  NaN_,
  hasIndices,
  ignoreCase,
  multiline,
  dotAll,
  sticky,
  unicodeSets,
  not_equal,
  timed_out,
  ok,
  toJSON,
  maxByteLength,
  // class names
  Object,
  Array,
  Error,
  Number,
  String,
  Boolean,
  Symbol,
  Arguments,
  Math,
  JSON,
  Date,
  Function,
  GeneratorFunction,
  ForInIterator,
  RegExp,
  ArrayBuffer,
  SharedArrayBuffer,
  Uint8ClampedArray,
  Int8Array,
  Uint8Array,
  Int16Array,
  Uint16Array,
  Int32Array,
  Uint32Array,
  BigInt64Array,
  BigUint64Array,
  Float16Array,
  Float32Array,
  Float64Array,
  DataView,
  BigInt_,
  WeakRef,
  FinalizationRegistry,
  Map,
  Set,
  WeakMap,
  WeakSet,
  Iterator,
  IteratorHelper,
  IteratorConcat,
  IteratorWrap,
  Map_Iterator,
  Set_Iterator,
  Array_Iterator,
  String_Iterator,
  RegExp_String_Iterator,
  Generator,
  Proxy,
  Promise,
  PromiseResolveFunction,
  PromiseRejectFunction,
  AsyncFunction,
  AsyncFunctionResolve,
  AsyncFunctionReject,
  AsyncGeneratorFunction,
  AsyncGenerator,
  EvalError,
  RangeError,
  ReferenceError,
  SyntaxError,
  TypeError,
  URIError,
  InternalError,
  AggregateError,
  // private / well-known symbols
  Private_brand,
  Symbol_toPrimitive,
  Symbol_iterator,
  Symbol_match,
  Symbol_matchAll,
  Symbol_replace,
  Symbol_search,
  Symbol_split,
  Symbol_toStringTag,
  Symbol_isConcatSpreadable,
  Symbol_hasInstance,
  Symbol_species,
  Symbol_unscopables,
  Symbol_asyncIterator,

  end,
};

constexpr AtomEnum kAtomLastKeyword       = AtomEnum::_super;
constexpr AtomEnum kAtomLastStrictKeyword = AtomEnum::_yield;

// ─── Atom string table (must match AtomEnum order, index 0 = null placeholder) ──────────────────────────────────
// Index by static_cast<Atom>(AtomEnum::xxx) — no off-by-one, null atom (0) has an entry at index 0.
inline constexpr std::string_view kAtomNames[] = {
    "", // 0 = kAtomNull placeholder
    "null",
    "false",
    "true",
    "if",
    "else",
    "return",
    "var",
    "this",
    "delete",
    "void",
    "typeof",
    "new",
    "in",
    "instanceof",
    "do",
    "while",
    "for",
    "break",
    "continue",
    "switch",
    "case",
    "default",
    "throw",
    "try",
    "catch",
    "finally",
    "function",
    "debugger",
    "with",
    "class",
    "const",
    "enum",
    "export",
    "extends",
    "import",
    "super",
    "implements",
    "interface",
    "let",
    "package",
    "private",
    "protected",
    "public",
    "static",
    "yield",
    "await",
    "",
    "keys",
    "size",
    "length",
    "fileName",
    "lineNumber",
    "columnNumber",
    "message",
    "cause",
    "errors",
    "stack",
    "name",
    "toString",
    "toLocaleString",
    "valueOf",
    "eval",
    "prototype",
    "constructor",
    "configurable",
    "writable",
    "enumerable",
    "value",
    "get",
    "set",
    "of",
    "__proto__",
    "undefined",
    "number",
    "boolean",
    "string",
    "object",
    "symbol",
    "integer",
    "unknown",
    "arguments",
    "callee",
    "caller",
    "<eval>",
    "<ret>",
    "<var>",
    "<arg_var>",
    "<with>",
    "lastIndex",
    "target",
    "index",
    "input",
    "defineProperties",
    "apply",
    "join",
    "concat",
    "split",
    "construct",
    "getPrototypeOf",
    "setPrototypeOf",
    "isExtensible",
    "preventExtensions",
    "has",
    "deleteProperty",
    "defineProperty",
    "getOwnPropertyDescriptor",
    "ownKeys",
    "add",
    "done",
    "next",
    "values",
    "source",
    "flags",
    "global",
    "unicode",
    "raw",
    "rawJSON",
    "new.target",
    "this.active_func",
    "<home_object>",
    "<computed_field>",
    "<static_computed_field>",
    "<class_fields_init>",
    "<brand>",
    "#constructor",
    "as",
    "from",
    "meta",
    "*default*",
    "*",
    "Module",
    "then",
    "resolve",
    "reject",
    "promise",
    "proxy",
    "revoke",
    "async",
    "exec",
    "groups",
    "indices",
    "status",
    "reason",
    "globalThis",
    "bigint",
    "-0",
    "Infinity",
    "-Infinity",
    "NaN",
    "hasIndices",
    "ignoreCase",
    "multiline",
    "dotAll",
    "sticky",
    "unicodeSets",
    "not-equal",
    "timed-out",
    "ok",
    "toJSON",
    "maxByteLength",
    "Object",
    "Array",
    "Error",
    "Number",
    "String",
    "Boolean",
    "Symbol",
    "Arguments",
    "Math",
    "JSON",
    "Date",
    "Function",
    "GeneratorFunction",
    "ForInIterator",
    "RegExp",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "Uint8ClampedArray",
    "Int8Array",
    "Uint8Array",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "BigInt64Array",
    "BigUint64Array",
    "Float16Array",
    "Float32Array",
    "Float64Array",
    "DataView",
    "BigInt",
    "WeakRef",
    "FinalizationRegistry",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Iterator",
    "Iterator Helper",
    "Iterator Concat",
    "Iterator Wrap",
    "Map Iterator",
    "Set Iterator",
    "Array Iterator",
    "String Iterator",
    "RegExp String Iterator",
    "Generator",
    "Proxy",
    "Promise",
    "PromiseResolveFunction",
    "PromiseRejectFunction",
    "AsyncFunction",
    "AsyncFunctionResolve",
    "AsyncFunctionReject",
    "AsyncGeneratorFunction",
    "AsyncGenerator",
    "EvalError",
    "RangeError",
    "ReferenceError",
    "SyntaxError",
    "TypeError",
    "URIError",
    "InternalError",
    "AggregateError",
    "<brand>",
    "Symbol.toPrimitive",
    "Symbol.iterator",
    "Symbol.match",
    "Symbol.matchAll",
    "Symbol.replace",
    "Symbol.search",
    "Symbol.split",
    "Symbol.toStringTag",
    "Symbol.isConcatSpreadable",
    "Symbol.hasInstance",
    "Symbol.species",
    "Symbol.unscopables",
    "Symbol.asyncIterator",
};

static_assert(static_cast<size_t>(AtomEnum::end) == std::size(kAtomNames),
              "kAtomNames must have null at [0] + one entry per AtomEnum (total = AtomEnum::end)");

/// Get the string name for a built-in atom, or empty view if out of range.
inline constexpr std::string_view atom_name(Atom a) { return (a < std::size(kAtomNames)) ? kAtomNames[a] : std::string_view{}; }

/// Get the token type for a built-in atom. Returns 0 to mean "use default TOK_IDENT".
/// Keywords are mapped to negative TOK_* values. 'of' is context-sensitive (TOK_OF = 3).
inline constexpr int atom_token(Atom a) {
  if (a == 0) return 0;
  // Keywords: atoms 1.._super map to negative tokens via the legacy formula
  if (a <= static_cast<Atom>(kAtomLastKeyword))
    return -85 + static_cast<int>(a) - 1;
  // 'of' is context-sensitive — positive token 3
  if (a == static_cast<Atom>(AtomEnum::of))
    return 3;
  // Everything else is a plain identifier
  return 0;
}

/// Get the AtomType for a given AtomEnum value (1..267).
inline constexpr AtomType atom_type_for(AtomEnum e) {
  if (e >= AtomEnum::Symbol_toPrimitive || e == AtomEnum::Private_brand)
    return AtomType::symbol;
  return AtomType::string;
}

} // namespace qjsp
